

Data Collection and Processing Technologies

---

# Introduction to TensorFlow
## Creating a small neural network

---

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
# one input one output

weight = 0.5
y_real = 0.8
input = 0.9
alpha = 0.1

for iteration in range(20):
    pred = input * weight
    error = (pred - y_real) ** 2
    
    weight_delta = (pred - y_real) * input
    
    weight = weight - weight_delta * alpha
    print(f"Error: {round(error, 5)}| Weight: {round(weight, 5)} | Prediction: {round(pred, 5)}")

Error: 0.1225| Weight: 0.5315 | Prediction: 0.45
Error: 0.10346| Weight: 0.56045 | Prediction: 0.47835
Error: 0.08738| Weight: 0.58705 | Prediction: 0.5044
Error: 0.0738| Weight: 0.6115 | Prediction: 0.52835
Error: 0.06232| Weight: 0.63397 | Prediction: 0.55035
Error: 0.05264| Weight: 0.65462 | Prediction: 0.57057
Error: 0.04446| Weight: 0.67359 | Prediction: 0.58916
Error: 0.03755| Weight: 0.69103 | Prediction: 0.60623
Error: 0.03171| Weight: 0.70706 | Prediction: 0.62193
Error: 0.02678| Weight: 0.72179 | Prediction: 0.63635
Error: 0.02262| Weight: 0.73532 | Prediction: 0.64961
Error: 0.0191| Weight: 0.74776 | Prediction: 0.66179
Error: 0.01613| Weight: 0.75919 | Prediction: 0.67299
Error: 0.01363| Weight: 0.7697 | Prediction: 0.68327
Error: 0.01151| Weight: 0.77935 | Prediction: 0.69273
Error: 0.00972| Weight: 0.78822 | Prediction: 0.70142
Error: 0.00821| Weight: 0.79638 | Prediction: 0.7094
Error: 0.00693| Weight: 0.80387 | Prediction: 0.71674
Error: 0.00585| Weight: 0.81076 | Predi

In [3]:
input_var = tf.Variable(initial_value = 3.0)

# y = x^2
# f'(x) = 2x

with tf.GradientTape() as tape:
    result = input_var ** 2
    
gradient = tape.gradient(result, input_var) # gradient(y, x)
print(gradient)

tf.Tensor(6.0, shape=(), dtype=float32)


In [4]:
# one input one output
weight = tf.Variable(initial_value= 0.5)
y_real = 0.8
input = 0.9
alpha = 0.1

for iteration in range(20):
    
    with tf.GradientTape() as tape:
        pred = input * weight
        error = (pred - y_real) ** 2
    
    
    weight_delta = tape.gradient(error, weight)
    print('w is', weight_delta)
    
    weight.assign_sub(alpha*weight_delta)
    print(f"Error: {round(float(error), 5)} | Weight: {round(float(weight), 5)} | Prediction: {round(float(pred), 5)}")

w is tf.Tensor(-0.63000005, shape=(), dtype=float32)
Error: 0.1225 | Weight: 0.563 | Prediction: 0.45
w is tf.Tensor(-0.52794003, shape=(), dtype=float32)
Error: 0.08602 | Weight: 0.61579 | Prediction: 0.5067
w is tf.Tensor(-0.44241375, shape=(), dtype=float32)
Error: 0.06041 | Weight: 0.66004 | Prediction: 0.55421
w is tf.Tensor(-0.37074274, shape=(), dtype=float32)
Error: 0.04242 | Weight: 0.69711 | Prediction: 0.59403
w is tf.Tensor(-0.31068242, shape=(), dtype=float32)
Error: 0.02979 | Weight: 0.72818 | Prediction: 0.6274
w is tf.Tensor(-0.26035184, shape=(), dtype=float32)
Error: 0.02092 | Weight: 0.75421 | Prediction: 0.65536
w is tf.Tensor(-0.21817484, shape=(), dtype=float32)
Error: 0.01469 | Weight: 0.77603 | Prediction: 0.67879
w is tf.Tensor(-0.18283051, shape=(), dtype=float32)
Error: 0.01032 | Weight: 0.79431 | Prediction: 0.69843
w is tf.Tensor(-0.15321197, shape=(), dtype=float32)
Error: 0.00725 | Weight: 0.80963 | Prediction: 0.71488
w is tf.Tensor(-0.12839155, shape=()

### Multiple inputs and outputs

In [5]:
def neural_network(input, weights):
    prediction = input.dot(weights.T)
    return prediction

def outer_prod(vec1, vec2):
    out = np.zeros((len(vec1), len(vec2)))
    
    for i in range(len(vec1)):
        for j in range(len(vec2)):
            out[i][j] = vec1[i] * vec2[j]
    return out

In [6]:
weights = np.zeros((3, 3))

input = np.array([8.5, 0.65, 1.2])
y_real = [0.1, 1, 0.1]

error = [0, 0, 0]
delta = [0, 0, 0]
alpha = 0.01


for iter in range(16):
    pred = neural_network(input, weights)

    for i in range(len(y_real)):
        error[i] = (pred[i] - y_real[i]) ** 2
        delta[i] = pred[i] - y_real[i]

    weight_deltas = outer_prod(delta, input)

    for i in range(len(weights)):
        for j in range(len(weights[0])):
            weights[i][j] -= alpha * weight_deltas[i][j]
    
    print("Iteration: " + str(iter))
    print("Prediction: " + str(pred))
    print("---")

Iteration: 0
Prediction: [0. 0. 0.]
---
Iteration: 1
Prediction: [0.0741125 0.741125  0.0741125]
---
Iteration: 2
Prediction: [0.09329837 0.93298373 0.09329837]
---
Iteration: 3
Prediction: [0.09826512 0.98265116 0.09826512]
---
Iteration: 4
Prediction: [0.09955088 0.99550882 0.09955088]
---
Iteration: 5
Prediction: [0.09988373 0.99883735 0.09988373]
---
Iteration: 6
Prediction: [0.0999699  0.99969902 0.0999699 ]
---
Iteration: 7
Prediction: [0.09999221 0.99992208 0.09999221]
---
Iteration: 8
Prediction: [0.09999798 0.99997983 0.09999798]
---
Iteration: 9
Prediction: [0.09999948 0.99999478 0.09999948]
---
Iteration: 10
Prediction: [0.09999986 0.99999865 0.09999986]
---
Iteration: 11
Prediction: [0.09999997 0.99999965 0.09999997]
---
Iteration: 12
Prediction: [0.09999999 0.99999991 0.09999999]
---
Iteration: 13
Prediction: [0.1        0.99999998 0.1       ]
---
Iteration: 14
Prediction: [0.1        0.99999999 0.1       ]
---
Iteration: 15
Prediction: [0.1 1.  0.1]
---


### Implement the above algorithm with TensorFlow

In [10]:
weights = tf.Variable(initial_value = tf.zeros((1,3)))
input = tf.Variable(initial_value = tf.constant([8.5, 0.65, 1.2], shape=[1, 3]))
y_real = tf.Variable(initial_value = tf.constant([0.1, 1, 0.1], shape=[1, 3]))
error =  tf.Variable(initial_value = tf.constant([0, 0, 0], shape=[1, 3]))
weight_deltas= tf.Variable(initial_value = tf.zeros((1,3)))
alpha = 0.01


for iter in range(200):
    with tf.GradientTape() as tape:
        pred = input * weights
        error = (pred - y_real) ** 2    

        
    weight_deltas = tape.gradient(error, weights)

    weights.assign_sub(alpha*weight_deltas)

    
    print("Iteration: " + str(iter))
    print("Prediction: " + str(pred))
    print("---")

Iteration: 0
Prediction: tf.Tensor([[0. 0. 0.]], shape=(1, 3), dtype=float32)
---
Iteration: 1
Prediction: tf.Tensor([[0.1445  0.00845 0.00288]], shape=(1, 3), dtype=float32)
---
Iteration: 2
Prediction: tf.Tensor([[0.08019751 0.0168286  0.00567706]], shape=(1, 3), dtype=float32)
---
Iteration: 3
Prediction: tf.Tensor([[0.10881212 0.02513639 0.00839356]], shape=(1, 3), dtype=float32)
---
Iteration: 4
Prediction: tf.Tensor([[0.09607861 0.03337399 0.01103182]], shape=(1, 3), dtype=float32)
---
Iteration: 5
Prediction: tf.Tensor([[0.10174502 0.04154198 0.01359411]], shape=(1, 3), dtype=float32)
---
Iteration: 6
Prediction: tf.Tensor([[0.09922347 0.04964095 0.0160826 ]], shape=(1, 3), dtype=float32)
---
Iteration: 7
Prediction: tf.Tensor([[0.10034556 0.05767148 0.01849942]], shape=(1, 3), dtype=float32)
---
Iteration: 8
Prediction: tf.Tensor([[0.09984623 0.06563415 0.02084664]], shape=(1, 3), dtype=float32)
---
Iteration: 9
Prediction: tf.Tensor([[0.10006843 0.07352954 0.02312625]], shape=

In [8]:
0.1445*0.009435  

0.0013633575